apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes
spec:
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
      - name: heroes
        image: mjn2k18/heroes
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
